/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Card from "../components/Card";
import Filter from "../components/Filter";
import styles from "../styles/Home.module.css";

export const getStaticProps = async () => {
  const data = await fetch("https://assessment-edvora.herokuapp.com/").then(
    (res) => res.json()
  );
  console.log(data);
  return {
    props: { data: data },
  };
};
export default function Home({ data }) {
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='flex bg-gray-700 h-screen p-10'>
          <div className='flex flex-col bg-gray-900 rounded-xl h-min p-4'>
            <h4 className='text-2xl font-thin text-gray-300 p-2'>Filter</h4>
            <hr />
            <Filter data={data} />
          </div>
          <div className='flex flex-1 flex-col px-10 overflow-hidden'>
            <h1 className='text-3xl text-gray-300'>Edvora</h1>
            <h3 className='text-2xl text-gray-500'>Products</h3>
            <div className='py-4'>
              <h4 className='text-2xl text-gray-300 p-2'>Product Name</h4>
              <hr />
              <div className='flex bg-gray-900 p-4 rounded-3xl mt-3 overflow-x-scroll gap-3'>
                {data
                  // .slice(1, 2)
                  // .filter((data) => data.product_name == "Tencent Limited")

                  .map((card, cardIdx) => (
                    <Card cardData={card} key={cardIdx} />
                  ))}
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
